"""init

迁移 ID: 072361e8936f
uff父迁移：None
创建时间：2026-04-01 14:22:31.037500

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "072361e8936f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###

    # 检查表是否存在
    bind = op.get_context().bind
    if bind is None:
        raise RuntimeError("Database bind is not available")
    inspector = sa.inspect(bind)
    table_names = inspector.get_table_names()

    # 创建 amrita_global_insights 表（如果不存在）
    if "amrita_global_insights" not in table_names:
        op.create_table(
            "amrita_global_insights",
            sa.Column("date", sa.String(length=64), nullable=False),
            sa.Column(
                "token_input",
                sa.BigInteger(),
                server_default=sa.text("0"),
                nullable=False,
            ),
            sa.Column(
                "token_output",
                sa.BigInteger(),
                server_default=sa.text("0"),
                nullable=False,
            ),
            sa.Column("usage_count", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("date", name=op.f("pk_amrita_global_insights")),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 创建 amrita_user_metadata 表（如果不存在）
    if "amrita_user_metadata" not in table_names:
        op.create_table(
            "amrita_user_metadata",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=64), nullable=False),
            sa.Column("last_active", sa.DateTime(), nullable=False),
            sa.Column("total_called_count", sa.BigInteger(), nullable=False),
            sa.Column("total_input_token", sa.BigInteger(), nullable=False),
            sa.Column("total_output_token", sa.BigInteger(), nullable=False),
            sa.Column("tokens_input", sa.BigInteger(), nullable=False),
            sa.Column("tokens_output", sa.BigInteger(), nullable=False),
            sa.Column("called_count", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_user_metadata")),
            sa.UniqueConstraint("user_id", name="uq_amrita_user_metadata_user_id"),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 使用 CREATE INDEX IF NOT EXISTS（而非 batch_alter_table），
    # 避免 SQLite batch 模式重建表时与模型 __table_args__ 索引冲突
    if "amrita_user_metadata" in table_names:
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_amrita_user_id_last_active "
            "ON amrita_user_metadata (user_id, last_active)"
        )

    # 创建 amrita_memory_data 表（如果不存在）
    if "amrita_memory_data" not in table_names:
        op.create_table(
            "amrita_memory_data",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=64), nullable=False),
            sa.Column(
                "memory_json", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
            ),
            sa.Column("extra_prompt", sa.Text(), nullable=False),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["amrita_user_metadata.user_id"],
                name=op.f("fk_amrita_memory_data_user_id_amrita_user_metadata"),
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_memory_data")),
            sa.UniqueConstraint("user_id", name="uq_amrita_memory_user_id"),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 创建 amrita_memory_sessions 表（如果不存在）
    if "amrita_memory_sessions" not in table_names:
        op.create_table(
            "amrita_memory_sessions",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.String(length=64), nullable=False),
            sa.Column("created_at", sa.Float(), nullable=False),
            sa.Column(
                "data", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
            ),
            sa.ForeignKeyConstraint(
                ["user_id"],
                ["amrita_user_metadata.user_id"],
                name=op.f("fk_amrita_memory_sessions_user_id_amrita_user_metadata"),
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=op.f("pk_amrita_memory_sessions")),
            info={"bind_key": "nonebot_plugin_amrita"},
        )

    # 使用 CREATE INDEX IF NOT EXISTS（而非 batch_alter_table）
    if "amrita_memory_sessions" in table_names:
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_am_sessions_created_at_time "
            "ON amrita_memory_sessions (created_at)"
        )
        op.execute(
            "CREATE INDEX IF NOT EXISTS idx_am_sessions_user_id "
            "ON amrita_memory_sessions (user_id)"
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###

    # 获取数据库检查器
    bind = op.get_context().bind
    if bind is None:
        raise RuntimeError("Database bind is not available")
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    # 删除表（仅当存在时），先用 DROP INDEX IF EXISTS 清理索引
    if "amrita_memory_sessions" in tables:
        op.execute("DROP INDEX IF EXISTS idx_am_sessions_user_id")
        op.execute("DROP INDEX IF EXISTS idx_am_sessions_created_at_time")
        op.drop_table("amrita_memory_sessions")

    if "amrita_memory_data" in tables:
        op.drop_table("amrita_memory_data")

    if "amrita_user_metadata" in tables:
        op.execute("DROP INDEX IF EXISTS idx_amrita_user_id_last_active")
        op.drop_table("amrita_user_metadata")

    if "amrita_global_insights" in tables:
        op.drop_table("amrita_global_insights")

    # ### end Alembic commands ###
